### ISSUE TITLE
Simultaneous top and lateral index locations not supported

### ISSUE THREAD

**Issue by radusuciu** [BioComputingUP/ProSeqViewer#1]
According to the docs 

> top place the index on top of each chunk (first row only). lateral place the index on the left, between the label and the sequence. both add both indexes

however, setting `indexesLocation` to `'both'` has no effect.

Thanks for the nicely designed component!

**Comment by mb925** [comment]
Hi!

Sorry for the late answer. I checked and you are right, unfortunately the only options available were 'lateral' and 'top'.
I have now implemented the option 'both' in the version 1.1.8 of the package and it should work fine. If you find any other problem with the package, please get in touch.

 Thank you for contributing in making this component better!

**Comment by radusuciu** [comment]
Hi, thanks, I'll test it out and get back to you! No worries on the "late" part - it's open source :)

The use-case I had in mind for this feature (the "both" setting) was for larger sequences that are presented on a wider screen - I find that it is helpful to have both position markers.
